name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.6.0
          cache: 'pnpm'
      - name: Install dependencies
        run: npm install

      - name: Build
        run: pnpm run docs:build



      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: /home/runner/work/blog/blog/.vitepress/dist
          target: /home/ubuntu/blog/.vitepress/dist
